[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

; IMPORTANT: garder les addons core + ajouter OCA
; addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/custom-addons

data_dir = /var/lib/odoo
