services:
  caddy:
    image: caddy:2
    container_name: gateway-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dorevia-network
    # extra_hosts supprimé (plus besoin de host.docker.internal)

volumes:
  caddy_data:
  caddy_config:

networks:
  dorevia-network:
    external: true
