# Patch pour upgrade Go 1.25.6 - Dorevia Vault
# Date : 2026-01-12
# Priorité : P0 (Sécurité)

# Modification Dockerfile
--- a/Dockerfile
+++ b/Dockerfile
@@ -2,7 +2,7 @@
 # Sprint 4 - US-4.1
 # Version : 1.0
 
-FROM golang:1.23-alpine AS builder
+FROM golang:1.25.6-alpine AS builder
 
 # Installer les dépendances nécessaires
 RUN apk add --no-cache git make
