# Configuration Odoo odoo prod rozas
# Template généré automatiquement par dorevia.sh
# Source attendue: odoo.prod.rozas
# DB name: odoo_prod_rozas

[options]
# Base de données
db_host = odoo_db_prod_rozas
db_port = 5432
db_user = odoo
db_password = odoo
dbfilter = ^odoo_prod_rozas$
admin_passwd = doreviateam@2026

# Addons
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/custom-addons

# Data
data_dir = /var/lib/odoo

# Logs (optionnel)
# logfile = /var/log/odoo/odoo.log
# log_level = info

