# Configuration Odoo odoo stinger conceptsun97139
# Template généré automatiquement par dorevia.sh
# Source attendue: odoo.stinger.conceptsun97139
# DB name: odoo_stinger_conceptsun97139

[options]
# Base de données
db_host = odoo_db_stinger_conceptsun97139
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo_stinger_conceptsun97139
dbfilter = ^odoo_stinger_conceptsun97139$
list_db = False

# Mot de passe maître pour le gestionnaire de base de données
admin_passwd = doreviateam@2026

# Addons
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/custom-addons

# Data
data_dir = /var/lib/odoo

# Reverse proxy (Caddy)
proxy_mode = True

# Queue Job (SPEC Orchestration temps réel DVIG via queue_job Odoo v1.0)
server_wide_modules = web,queue_job
workers = 2

# Logs (optionnel)
# logfile = /var/log/odoo/odoo.log
# log_level = info

[queue_job]
channels = root:2
