[options]
db_host = odoo_db_lab_laplatine2026
db_port = 5432
db_user = odoo
db_password = odoo
dbfilter = ^laplatine2026$
list_db = False

; addons
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/custom-addons
data_dir = /var/lib/odoo

proxy_mode = True

; Queue Job (SPEC Orchestration temps réel DVIG via queue_job Odoo v1.0) — aligné sarl-la-platine
server_wide_modules = web,queue_job
workers = 2

[queue_job]
channels = root:2,dorevia_vault:2
