[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
list_db = True
admin_passwd = admin
http_port = 8069
proxy_mode = False
workers = 0
max_cron_threads = 1
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/addons-thirdparty,/mnt/addons-o19,/mnt/custom-addons
data_dir = /var/lib/odoo
dbfilter = ^odoo19_accounting_kit$
