/**
 * Metric Engine — Registry
 * SPEC_LINKY_METRIC_REGISTRY_v1.0
 *
 * Registre des 12 métriques financières Linky.
 * Toute nouvelle métrique doit être ajoutée ici avant implémentation.
 */

import type { MetricDefinition } from "./types";

export const METRIC_REGISTRY: MetricDefinition[] = [
  // ─── Base metrics ────────────────────────────────────────────────────────

  {
    metric_id: "treasury_balance",
    label: "Solde trésorerie",
    metric_class: "base",
    metric_type: "position",
    metric_category: "liquidity",
    value_type: "currency",
    formula: "Σ(payment.received) - Σ(payment.sent)",
    dependencies: [],
    events: ["payment_received", "payment_sent"],
    calculation_scope: "realtime",
    unit: "EUR",
    instrument: "treasury",
    cache_ttl_s: 120,
  },
  {
    metric_id: "commercial_margin",
    label: "Marge commerciale",
    metric_class: "base",
    metric_type: "flow",
    metric_category: "activity",
    value_type: "currency",
    formula: "Σ(ventes_ht) - Σ(achats_ht)",
    dependencies: [],
    events: ["invoice_issued"],
    calculation_scope: "realtime",
    unit: "EUR",
    instrument: "business",
    cache_ttl_s: 300,
  },
  {
    metric_id: "cash_flow_net",
    label: "Flux de trésorerie net",
    metric_class: "base",
    metric_type: "flow",
    metric_category: "liquidity",
    value_type: "currency",
    formula: "Σ(encaissements) - Σ(décaissements)",
    dependencies: [],
    events: ["payment_received", "payment_sent"],
    calculation_scope: "realtime",
    unit: "EUR",
    instrument: "cash_flow",
    cache_ttl_s: 120,
  },
  {
    metric_id: "tax_balance",
    label: "Solde TVA",
    metric_class: "base",
    metric_type: "flow",
    metric_category: "adjustments",
    value_type: "currency",
    formula: "Σ(tva_collectee) - Σ(tva_deductible)",
    dependencies: [],
    events: ["invoice_issued"],
    calculation_scope: "realtime",
    unit: "EUR",
    instrument: "taxes",
    cache_ttl_s: 300,
  },
  {
    metric_id: "credit_notes_balance",
    label: "Solde avoirs",
    metric_class: "base",
    metric_type: "flow",
    metric_category: "adjustments",
    value_type: "currency",
    formula: "Σ(avoirs_fournisseurs) - Σ(avoirs_clients)",
    dependencies: [],
    events: ["credit_note.customer.issued", "credit_note.supplier.received"],
    calculation_scope: "realtime",
    unit: "EUR",
    instrument: "credit_notes",
    cache_ttl_s: 300,
  },
  {
    metric_id: "refunds_balance",
    label: "Solde remboursements",
    metric_class: "base",
    metric_type: "flow",
    metric_category: "adjustments",
    value_type: "currency",
    formula: "Σ(remb_fournisseurs) - Σ(remb_clients)",
    dependencies: [],
    events: ["refund.customer.paid", "refund.supplier.received"],
    calculation_scope: "realtime",
    unit: "EUR",
    instrument: "refunds",
    cache_ttl_s: 300,
  },
  {
    metric_id: "receivables_open",
    label: "Créances clients ouvertes",
    metric_class: "base",
    metric_type: "exposure",
    metric_category: "risk",
    value_type: "currency",
    formula: "Σ(amount_residual) sur out_invoice — GET /ui/aggregations/ar-by-partner",
    dependencies: [],
    events: ["invoice_issued"],
    calculation_scope: "realtime",
    unit: "EUR",
    instrument: "encours",
    cache_ttl_s: 180,
  },
  {
    metric_id: "payables_open",
    label: "Dettes fournisseurs ouvertes",
    metric_class: "base",
    metric_type: "exposure",
    metric_category: "risk",
    value_type: "currency",
    formula: "Σ(amount_residual) sur in_invoice — GET /ui/aggregations/ap-by-partner",
    dependencies: [],
    events: ["invoice_issued"],
    calculation_scope: "realtime",
    unit: "EUR",
    instrument: "working_capital",
    cache_ttl_s: 180,
  },
  {
    metric_id: "payroll_charges",
    label: "Charges de personnel",
    metric_class: "base",
    metric_type: "flow",
    metric_category: "performance",
    value_type: "currency",
    formula: "Σ(total_charges) hr.payslip — GET /ui/aggregations/payroll",
    dependencies: [],
    events: ["payroll.charge.posted"],
    calculation_scope: "batch",
    unit: "EUR",
    instrument: "ebitda",
    cache_ttl_s: 3600,
  },
  {
    metric_id: "pos_sales_total",
    label: "CA POS total",
    metric_class: "base",
    metric_type: "flow",
    metric_category: "activity",
    value_type: "currency",
    formula: "Σ(total_sales) sessions scellées",
    dependencies: [],
    events: ["pos_session"],
    calculation_scope: "realtime",
    unit: "EUR",
    instrument: "pos_activity",
    cache_ttl_s: 60,
  },

  // ─── Derived metrics ──────────────────────────────────────────────────────

  {
    metric_id: "working_capital",
    label: "BFR",
    metric_class: "derived",
    metric_type: "position",
    metric_category: "liquidity",
    value_type: "currency",
    formula: "receivables_open - payables_open",
    dependencies: ["receivables_open", "payables_open"],
    events: [],
    calculation_scope: "realtime",
    unit: "EUR",
    instrument: "working_capital",
    cache_ttl_s: 180,
  },
  {
    metric_id: "treasury_validated_pct",
    label: "Taux de validation trésorerie",
    metric_class: "derived",
    metric_type: "performance",
    metric_category: "liquidity",
    value_type: "ratio",
    formula: "1 - remaining_ratio (depuis bank reconciliation)",
    dependencies: ["treasury_balance"],
    events: ["bank.move.reconciled"],
    calculation_scope: "realtime",
    unit: "%",
    instrument: "treasury",
    cache_ttl_s: 120,
  },
  {
    metric_id: "commercial_margin_pct",
    label: "Taux de marge commerciale",
    metric_class: "derived",
    metric_type: "performance",
    metric_category: "activity",
    value_type: "ratio",
    formula: "commercial_margin / Σ(ventes_ht) * 100",
    dependencies: ["commercial_margin"],
    events: [],
    calculation_scope: "realtime",
    unit: "%",
    instrument: "business",
    cache_ttl_s: 300,
  },
  {
    metric_id: "ebitda_proxy",
    label: "EBE (proxy)",
    metric_class: "derived",
    metric_type: "performance",
    metric_category: "performance",
    value_type: "currency",
    formula: "commercial_margin + credit_notes_balance — sans payroll_charges",
    dependencies: ["commercial_margin", "credit_notes_balance"],
    events: [],
    calculation_scope: "batch",
    unit: "EUR",
    instrument: "ebitda",
    cache_ttl_s: 600,
  },
  {
    metric_id: "ebitda_full",
    label: "EBE complet",
    metric_class: "derived",
    metric_type: "performance",
    metric_category: "performance",
    value_type: "currency",
    formula: "commercial_margin + credit_notes_balance - payroll_charges",
    dependencies: ["commercial_margin", "credit_notes_balance", "payroll_charges"],
    events: [],
    calculation_scope: "batch",
    unit: "EUR",
    instrument: "ebitda",
    cache_ttl_s: 3600,
  },
];

/** Index par metric_id pour lookup O(1) */
export const METRIC_INDEX: Map<string, MetricDefinition> = new Map(
  METRIC_REGISTRY.map((m) => [m.metric_id, m])
);

/** Récupère une définition par ID (lève si introuvable) */
export function getMetric(metric_id: string): MetricDefinition {
  const m = METRIC_INDEX.get(metric_id);
  if (!m) throw new Error(`Metric not found in registry: ${metric_id}`);
  return m;
}

/** Toutes les métriques d'un instrument */
export function getMetricsByInstrument(instrument: string): MetricDefinition[] {
  return METRIC_REGISTRY.filter((m) => m.instrument === instrument);
}
